$(function(){var k=parseFloat($("#detail_realtime_price").val()),h=$("#buyGramsNumber"),l=$("#buyMoneyNumber"),b=$("#buyGrams_errorMsg"),c=$("#buyValue_errorMsg");$(".left-tab-item").bind("click",function(){$(this).parent().find(".left-tab-item").removeClass("active");$(this).addClass("active");var a=$(this).find("a").attr("type");$(".left-tab-up1").removeClass("left-tab-up3");"gram"==a?($("#buyGrams").show(),$("#buyValue").hide(),$("#valueInput").val(""),l.html(0),c.html(""),c.hide()):"money"==a&&
($(".left-tab-up1").addClass("left-tab-up3"),$("#buyGrams").hide(),$("#buyValue").show(),$("#gramInput").val(""),h.html(0),b.html(""),b.hide())});$(".trade-button").click(function(){var a=$(this),m=a.prevAll("input[name='type']"),r=a.prevAll("input[name='orderNo']"),r=a.prevAll("input[name='orderNo']"),e=a.prevAll("input[name='buyWeight']"),f=a.prevAll("input[name='currentPrice']"),h=a.prevAll("input[name='realMoney']"),k=a.prevAll("input[name='totalMoney']"),t=a.prevAll("input[name='interestStart']"),
u=a.prevAll("input[name='interestEnd']"),v=a.prevAll("input[name='createTime']"),n=a.prevAll("input[name='depositType']"),g=m.val(),m=$("#gramInput").val(),q=$("#valueInput").val(),p=parseInt($("#depositType").val());"gram"!==g||parseFloat(m)?"gram"===g&&1E8<=parseFloat(m)?(b.html("*\u8d2d\u4e70\u91cd\u91cf\u8d85\u9650"),b.show()):"money"!==g||parseFloat(q)?"money"===g&&1E8<=parseFloat(q)?(c.html("*\u8d2d\u4e70\u91d1\u989d\u8d85\u9650"),c.show()):"money"!==g||parseFloat(l.html())?(n.val(p),n="/trade/gold/buyGold",
0!=p&&(n="/deposit/buyDepositGold"),$.post(n,{depositType:p,type:g,gramInput:m,valueInput:q},function(d){d.success?(r.val(d.orderNo),e.val(d.buyWeight),f.val(d.currentPrice),h.val(d.realMoney),k.val(d.totalMoney),v.val(d.createTime),0==p?t.val(d.estimateInterestDate):(t.val(d.interestStart),u.val(d.interestEnd)),a.parents("form").submit()):"0038"==d.code?$("#no-card").show():"0002"!=d.code&&""!=d.msg&&("gram"===g?(b.html("*"+d.msg),b.show()):"money"===g&&(c.html("*"+d.msg),c.show()))})):(c.html("*\u8d2d\u4e70\u91cd\u91cf\u6700\u5c111\u6beb\u514b"),
c.show()):(c.html("*\u8d2d\u4e70\u91cd\u91cf\u6700\u5c111\u6beb\u514b"),c.show()):(b.html("*\u8d2d\u4e70\u91cd\u91cf\u6700\u5c111\u6beb\u514b"),b.show());return!1});$("#close1").click(function(){$("#no-card").css("display","none")});$("#gramInput").bind({keypress:function(a){a=a.charCode?a.charCode:a.keyCode;var c=$(this).val();return 46==a||8==a||48<=a&&57>=a?2==c.split(".").length&&46==a?!1:!0:!1},keyup:function(a){clearNoNum(this,3);11<this.value.length&&(this.value=this.value.substring(0,13));
(a=parseFloat($(this).val()))?(realPrice||(realPrice=k),h.html(Math.ceil(a*realPrice)/100)):h.html(0)},focus:function(){b.html("");b.hide()},blur:function(a){clearNoNum(this,3);11<this.value.length&&(this.value=this.value.substring(0,13));(a=parseFloat($(this).val()))?(realPrice||(realPrice=k),h.html(Math.ceil(a*realPrice)/100)):h.html(0)}});$("#valueInput").bind({keypress:function(a){a=a.charCode?a.charCode:a.keyCode;var c=$(this).val();return 46==a||8==a||48<=a&&57>=a?2==c.split(".").length&&46==
a?!1:!0:!1},keyup:function(a){clearNoNum(this,2);11<this.value.length&&(this.value=this.value.substring(0,13));(a=parseFloat($(this).val()))?(realPrice||(realPrice=k),l.html(Math.floor(1E5*a/realPrice)/1E3)):l.html(0)},focus:function(){c.html("");c.hide()},blur:function(a){clearNoNum(this,2);11<this.value.length&&(this.value=this.value.substring(0,13));(a=parseFloat($(this).val()))?(realPrice||(realPrice=k),l.html(Math.floor(1E5*a/realPrice)/1E3)):l.html(0)}});var e=0;isNaN(parseInt($("#depositType").val()))||
(e=parseInt($("#depositType").val()));$("#depositType").val(e);$.ajax({type:"GET",url:"/deposit/getDepositReport",dataType:"json",data:{depositType:e},success:function(a,c){if(a.success){var b=a.depositList;$("#depositRate").html(b.rate/100);$("#depositName").html(b.depositName);$("#depositWeight").html((b.totalWeight/1E3).toFixed(0));$("#depositUser").html(b.totalUser);$("#gramInput").attr("placeholder",a.weightDescription);$("#valueInput").attr("placeholder",a.moneyDescription);$(".demand-into").each(function(){2!=
a.tradeType&&($(this).attr("href","/account/depositInto?type="+e),$(this).css("display","block"))});0==a.buyType?($("#buyValue .trade-button").attr("disabled","true"),$("#buyValue .trade-button").css("background","#f7f1e9"),$("#buyValue .trade-button").css("color","#867a6a")):1==a.buyType&&($("#buyGrams .trade-button").attr("disabled","true"),$("#buyGrams .trade-button").css("background","#f7f1e9"),$("#buyGrams .trade-button").css("color","#867a6a"))}}});$.ajax({type:"GET",url:"/info/getPromptInfo",
dataType:"json",success:function(a,c){if("0000"==a.code&&void 0!=a.estimateInterestDatePrompt){for(var b=a.estimateInterestDatePrompt.split("\n"),e=[],f=1;f<b.length-1;f++)e[e.length]="<div style='width:288px;line-height:30px;margin-left:27px;'>"+b[f]+"</div>";$(".prompt_top").after(e.join(""))}}});var f=0;isNaN(parseInt($("#useDeductible").val()))||(f=parseInt($("#useDeductible").val()));$("#useDeductible").val(f);0!=f&&(f=1,0!=e&&(f=3),$.ajax({type:"GET",url:"/deductible/maxDeductible",dataType:"json",
data:{type:f,depositType:e},success:function(a,b){"0000"==a.code&&void 0!=a.message&&""!=a.message&&$(".deductible-message").each(function(){$(this).html(a.message)})}}))});
